# Shared/common parameters used across multiple endpoints

UserId:
  name: id
  in: path
  description: User ID (UUID format)
  required: true
  schema:
    type: string
    format: uuid
  example: 550e8400-e29b-41d4-a716-446655440000
