// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Stores user account information
type User struct {
	// Unique identifier for the user (UUID v4)
	ID pgtype.UUID `json:"id"`
	// User email address (unique, used for login)
	Email string `json:"email"`
	// User full name or display name
	Name string `json:"name"`
	// Bcrypt hashed password
	PasswordHash string `json:"password_hash"`
	// Soft delete flag - false means user is deleted
	IsActive bool `json:"is_active"`
	// Timestamp when user was created
	CreatedAt pgtype.Timestamp `json:"created_at"`
	// Timestamp when user was last updated
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
